/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sof3.clinivet.frames;

/**
 *
 * @author xps-l502x
 */
public class frmExibirCliente extends javax.swing.JFrame {

    /**
     * Creates new form frmExibirCliente
     */
    public frmExibirCliente() {
        initComponents();
        setVisible(true);
        setDefaultCloseOperation(WIDTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulojanela = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblTituloTabela = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnimal = new javax.swing.JTable();
        txtCliente = new javax.swing.JLabel();
        txtcpf = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JLabel();
        txtEnd = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        txtCelu = new javax.swing.JLabel();
        txtBairro = new javax.swing.JLabel();
        txtCid1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulojanela.setText("Detalhes do cliente selecionado");

        lblNome.setText("Nome");

        lblCpf.setText("CPF");

        lblTelefone.setText("Telefone");

        lblCelular.setText("Celular");

        lblEndereco.setText("Endereço");

        lblEmail.setText("E-mail");

        lblBairro.setText("Bairro");

        lblCidade.setText("Cidade");

        lblTituloTabela.setText("Animais Cadastrados:");

        tblAnimal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo Animal", "Raça", "Nome", "Sexo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAnimal);
        tblAnimal.getColumnModel().getColumn(0).setResizable(false);
        tblAnimal.getColumnModel().getColumn(1).setResizable(false);

        txtCliente.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        txtCliente.setForeground(new java.awt.Color(69, 68, 222));
        txtCliente.setText("NomeCliente");

        txtcpf.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        txtcpf.setForeground(new java.awt.Color(69, 68, 222));
        txtcpf.setText("CPFCliente");

        txtEndereco.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        txtEndereco.setForeground(new java.awt.Color(69, 68, 222));
        txtEndereco.setText("ENDCliente");

        txtTelefone.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        txtTelefone.setForeground(new java.awt.Color(69, 68, 222));
        txtTelefone.setText("TelCli");

        txtEnd.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        txtEnd.setForeground(new java.awt.Color(69, 68, 222));
        txtEnd.setText("EMAILCli");

        txtTotal.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(69, 68, 222));
        txtTotal.setText("Total de Aniam");

        txtCelu.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        txtCelu.setForeground(new java.awt.Color(69, 68, 222));
        txtCelu.setText("CelCli");

        txtBairro.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        txtBairro.setForeground(new java.awt.Color(69, 68, 222));
        txtBairro.setText("BairCli");

        txtCid1.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        txtCid1.setForeground(new java.awt.Color(69, 68, 222));
        txtCid1.setText("CidClien");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEndereco)
                                    .addComponent(lblEmail))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(txtEndereco))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtcpf)
                                            .addComponent(txtCliente)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCid1)
                                            .addComponent(txtEnd)))))
                            .addComponent(lblCpf)
                            .addComponent(lblNome)
                            .addComponent(lblTitulojanela)
                            .addComponent(lblCidade)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTituloTabela)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal)))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBairro))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCelular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCelu))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelefone)))
                        .addGap(0, 133, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitulojanela)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(lblTelefone)
                    .addComponent(txtcpf)
                    .addComponent(txtTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCelular)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco)
                    .addComponent(txtCelu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(lblBairro)
                    .addComponent(txtEnd)
                    .addComponent(txtBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(txtCid1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloTabela)
                    .addComponent(txtTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmExibirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmExibirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmExibirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmExibirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmExibirCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTituloTabela;
    private javax.swing.JLabel lblTitulojanela;
    private javax.swing.JTable tblAnimal;
    private javax.swing.JLabel txtBairro;
    private javax.swing.JLabel txtCelu;
    private javax.swing.JLabel txtCid1;
    private javax.swing.JLabel txtCliente;
    private javax.swing.JLabel txtEnd;
    private javax.swing.JLabel txtEndereco;
    private javax.swing.JLabel txtTelefone;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JLabel txtcpf;
    // End of variables declaration//GEN-END:variables
}
