/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sof3.clinivet.frames;

import br.com.sof3.clinivet.dao.VendedorDAO;
import br.com.sof3.clinivet.entidade.Animal;
import br.com.sof3.clinivet.entidade.Cliente;
import br.com.sof3.clinivet.entidade.Vendedor;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *public void carregaCampos(Animal ani){
        txtNome.setText(ani.getNome());
        txtNasc.setText(ani.getDataNasc());
        comboTipoAnimal.setSelectedItem(ani.getTipoAnimal());
        comboRaca.setSelectedItem(ani.getRaca().getNome());
        checkMacho.setSelected(ani.getSexo().equals("Macho") ? true : false);
        checkFemea.setSelected(ani.getSexo().equals("Fêmea")?true:false);
        
    }
 * @author andrematos
 */
public class frmPesquisaVendedor extends javax.swing.JFrame {
    VendedorDAO vdao = new VendedorDAO();
    /**
     * Creates new form frmPesquisaVendedor
     */
    public frmPesquisaVendedor(String parametro) {
        initComponents();
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        setVisible(true);
        setLocationRelativeTo(null);
        rbtNome.setSelected(true);
        if(parametro.equals("editar")){//configurações carregadas caso o parametro for editar
            btnEditar.setVisible(true);
            lblBuscarVendedor.setText("Editar Usuário");
        }else if(parametro.equals("pesquisar")){
            btnEditar.setVisible(false);
            btnExluir.setVisible(false);
            lblBuscarVendedor.setText("Buscar Usuário");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuscaVendedor = new javax.swing.JTable();
        lblBuscarVendedor = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbtNome = new javax.swing.JRadioButton();
        rbtLogin = new javax.swing.JRadioButton();
        btnUltimosCad = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscaVendedor = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnExluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblBuscaVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Login"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBuscaVendedor);
        tblBuscaVendedor.getColumnModel().getColumn(0).setResizable(false);
        tblBuscaVendedor.getColumnModel().getColumn(0).setPreferredWidth(200);
        tblBuscaVendedor.getColumnModel().getColumn(1).setResizable(false);

        lblBuscarVendedor.setText("Buscar Vendedores");

        buttonGroup1.add(rbtNome);
        rbtNome.setText("Nome");
        rbtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNomeActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtLogin);
        rbtLogin.setText("Login");
        rbtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rbtLogin)
                .addGap(28, 28, 28)
                .addComponent(rbtNome)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbtNome)
                .addComponent(rbtLogin))
        );

        btnUltimosCad.setText("Ultimos Cadastros");
        btnUltimosCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimosCadActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExluir.setText("Excluir");
        btnExluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(txtBuscaVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBuscar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBuscarVendedor)
                        .addGap(379, 379, 379)
                        .addComponent(btnUltimosCad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(266, 266, 266)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnExluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarVendedor)
                    .addComponent(btnUltimosCad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscaVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar))
                    .addComponent(btnExluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUltimosCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimosCadActionPerformed
        // TODO add your handling code here:

        DefaultTableModel dtm = (DefaultTableModel)tblBuscaVendedor.getModel();

        for(int aux=0;aux<dtm.getRowCount();aux++)
        dtm.removeRow(aux);

        try {

            List<Vendedor>  listv = new LinkedList<Vendedor>();

            Vendedor v = new Vendedor();
            limparTabela();
//            int cont = dtm.getRowCount();
//            for(int aux=cont-1 ;   aux>=0;  aux--){//removendo valores da tabela
//                dtm.removeRow(aux);
//            }

            listv = vdao.getVendedorByID();

            for(int aux=0 ;aux<listv.size();aux++){
                if(aux<6){
                    v.setNome(listv.get(aux).getNome());
                    v.setLogin(listv.get(aux).getLogin());
                    if(!listv.get(aux).isInativo()){
                         dtm.addRow(v.addTable());
                         JOptionPane.showMessageDialog(null, listv.get(aux).isInativo());
                    }
                }

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no try da classe frmPesquisaCliente no botao buscar");
        }

    }//GEN-LAST:event_btnUltimosCadActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        DefaultTableModel dtm = (DefaultTableModel)tblBuscaVendedor.getModel();

        int cont2 = dtm.getRowCount();
        for(int aux=cont2-1 ;   aux>=0;  aux--){//removendo valores da tabela
            dtm.removeRow(aux);
        }

        if(txtBuscaVendedor.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite para pesquisar");

        }else{
            int cont=0;
            try {

                 List<Vendedor>  listv = new LinkedList<Vendedor>();

                 Vendedor v = new Vendedor();
                 if(rbtNome.isSelected()){
                   listv = vdao.getVendedorByName(txtBuscaVendedor.getText());
                 }else{
                     listv = vdao.getVendedorByLogin(txtBuscaVendedor.getText());
                 }
                        
                for(int aux =0;aux<listv.size();aux++){
                    v.setLogin(listv.get(aux).getLogin());
                    v.setNome(listv.get(aux).getNome());

                    dtm.addRow(v.addTable());
                    cont++;
                }
                
                if(cont==0)//para exibir caso procura não exiba nada
                JOptionPane.showMessageDialog(null, "Nenhum Registro encontrado");

            }catch (SQLException ex){
                
                JOptionPane.showMessageDialog(null, "Erro no try da classe frmPesquisaVendedor no botao buscar");
            }

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void rbtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtLoginActionPerformed

    private void rbtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtNomeActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(tblBuscaVendedor.getSelectedRow() >= 0 && tblBuscaVendedor.getSelectedRow()<tblBuscaVendedor.getRowCount()){
            Vendedor vendedor = new Vendedor();
            List<Vendedor> vend = new LinkedList<Vendedor>();
            try{
                DefaultTableModel dtm = (DefaultTableModel)tblBuscaVendedor.getModel();
                String login = String.valueOf(dtm.getValueAt(tblBuscaVendedor.getSelectedRow(), 1));

                vend=vdao.getVendedorByLogin(login);
                
                String senhaInformada = JOptionPane.showInputDialog(null, "Por favor informe a senha");
                    if (senhaInformada.equals(vend.get(0).getSenha())) {
                         frmAddVendedor frmEditarVendedor = new frmAddVendedor("editar", vend.get(0));
                    } else {
                        JOptionPane.showMessageDialog(null, "Impossivel Editar, Senhas não correspondem!!");
                    }
                  
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Erro no botão editar na classe frmPesquisaVendedor");
            }
        }else JOptionPane.showMessageDialog(null, "Selecione um Vendedor para editar");
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExluirActionPerformed
        VendedorDAO vendedorDAO = new VendedorDAO();
        if(tblBuscaVendedor.getSelectedRow()>=0 && tblBuscaVendedor.getSelectedRow()<tblBuscaVendedor.getRowCount()){
            List<Vendedor> vend = new LinkedList<>();
            DefaultTableModel dtm = (DefaultTableModel)tblBuscaVendedor.getModel();
            try{
                 vend = vendedorDAO.getVendedorByLogin(String.valueOf(dtm.getValueAt(tblBuscaVendedor.getSelectedRow(), 1)));
                 vendedorDAO.inativarVendedor(vend.get(0).getId());
                 vend = vendedorDAO.getAllVendedores();
                 limparTabela();
                 atualizarTabela(vend);
            }catch(Exception ex){
                 JOptionPane.showMessageDialog(null,"Erro ao excluir vendedor na classe frmPesquisaVendedor: "+ ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um registro");
        }
                
    }//GEN-LAST:event_btnExluirActionPerformed
    public void atualizarTabela(List<Vendedor> vendedores){
        DefaultTableModel dtm = (DefaultTableModel)tblBuscaVendedor.getModel();
        for(int aux=0;aux<vendedores.size();aux++){
                    if(!vendedores.get(aux).isInativo())
                        dtm.addRow(vendedores.get(aux).addTable());
                }
    }
    public void limparTabela(){
        DefaultTableModel dtm =  (DefaultTableModel) tblBuscaVendedor.getModel();
        int cont = dtm.getRowCount();
            for(int aux=cont-1 ;   aux>=0 ;  aux--){//removendo valores da tabela
               dtm.removeRow(aux);
            }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExluir;
    private javax.swing.JButton btnUltimosCad;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarVendedor;
    private javax.swing.JRadioButton rbtLogin;
    private javax.swing.JRadioButton rbtNome;
    private javax.swing.JTable tblBuscaVendedor;
    private javax.swing.JTextField txtBuscaVendedor;
    // End of variables declaration//GEN-END:variables
}
