/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sof3.clinivet.frames;

import br.com.sof3.clinivet.dao.VendaDAO;
import br.com.sof3.clinivet.dao.VendedorDAO;
import br.com.sof3.clinivet.entidade.Venda;
import br.com.sof3.clinivet.entidade.Vendedor;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Renan
 */
public class frmVendasEfetuadas extends javax.swing.JFrame {
    VendaDAO vdao = new VendaDAO();
    VendedorDAO vendDao = new VendedorDAO();
    /**
     * Creates new form frmVendasEfetuadas
     */
    public frmVendasEfetuadas() {
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupBuscarVendas = new javax.swing.ButtonGroup();
        lblBuscarVendas = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        radioVendedor = new javax.swing.JRadioButton();
        radioDataVenda = new javax.swing.JRadioButton();
        radioVendasDoDia = new javax.swing.JRadioButton();
        radioTodasVendas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVendas = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        lblTotalVendido = new javax.swing.JLabel();
        lblTotalBusca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBuscarVendas.setText("Buscar Vendas:");

        groupBuscarVendas.add(radioVendedor);
        radioVendedor.setText("Vendedor");

        groupBuscarVendas.add(radioDataVenda);
        radioDataVenda.setText("Data Venda");

        groupBuscarVendas.add(radioVendasDoDia);
        radioVendasDoDia.setText("Vendas do Dia");

        groupBuscarVendas.add(radioTodasVendas);
        radioTodasVendas.setSelected(true);
        radioTodasVendas.setText("Todas Vendas");

        tableVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data da Venda", "Total da Venda", "Forma de Pagamento", "Vendedor", "Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableVendas);
        tableVendas.getColumnModel().getColumn(0).setResizable(false);
        tableVendas.getColumnModel().getColumn(1).setResizable(false);
        tableVendas.getColumnModel().getColumn(2).setResizable(false);
        tableVendas.getColumnModel().getColumn(3).setResizable(false);
        tableVendas.getColumnModel().getColumn(4).setResizable(false);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblTotalVendido.setText("Total Vendido: R$ 0,00");

        lblTotalBusca.setText("Total da Busca: 0 Resultado(s)");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(36, 36, 36)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(radioVendedor)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(radioDataVenda)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(radioVendasDoDia)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(radioTodasVendas))
                            .add(layout.createSequentialGroup()
                                .add(11, 11, 11)
                                .add(lblBuscarVendas)))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(4, 4, 4)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(lblTotalBusca)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(lblTotalVendido)
                                .add(150, 150, 150))
                            .add(layout.createSequentialGroup()
                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 796, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 39, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .add(txtBusca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(btnBuscar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(lblBuscarVendas)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(radioVendedor)
                    .add(radioDataVenda)
                    .add(radioVendasDoDia)
                    .add(radioTodasVendas))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtBusca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnBuscar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 241, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblTotalVendido)
                    .add(lblTotalBusca))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

            DefaultTableModel dtm = (DefaultTableModel)tableVendas.getModel();
            int cont = 0, quantResul = 0;
            double totalVendido = 0;
            
            int cont2 = dtm.getRowCount();
            for(int aux=cont2-1 ;   aux>=0;  aux--){//removendo valores da tabela
                dtm.removeRow(aux);
            }
            
            Venda v  = new Venda();
            List<Venda> ven = new LinkedList<Venda>();
            
            if(radioTodasVendas.isSelected()) {
                try {
                    ven = vdao.getAllVenda();
                } catch (SQLException ex) {
                    Logger.getLogger(frmVendasEfetuadas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(radioVendedor.isSelected()) {
                try {
                   int id_vendedor;
                   id_vendedor = vendDao.getIdVendedor(txtBusca.getText());
                   ven = vdao.getVendaByVendedor(id_vendedor);
                } catch (SQLException ex) {
                    Logger.getLogger(frmVendasEfetuadas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            if(radioVendasDoDia.isSelected()) {
                try {    
                    ven = vdao.getVendasDoDia();
                } catch (SQLException ex) {
                    Logger.getLogger(frmVendasEfetuadas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            for(int aux =0;aux<ven.size();aux++){
                v.setDataVenda(ven.get(aux).getDataVenda());
                v.setTotalVenda(ven.get(aux).getTotalVenda());
                v.setFormaPagamento(ven.get(aux).getFormaPagamento());
                v.setVendedor(ven.get(aux).getVendedor());
                v.setCliente(ven.get(aux).getCliente());                            
                        
                totalVendido += v.getTotalVenda();
                dtm.addRow(v.addTableVendasEfetuadas());
                cont++;
                quantResul++; 
            }
            
            if(ven.size()==0){
              lblTotalVendido.setText("Total Vendido: R$ 0,00");
              lblTotalBusca.setText("Total da Busca: 0 Resultado(s)");
            }
                    
            lblTotalVendido.setText("Total Vendido: R$ "+String.format("%.2f", totalVendido));
            lblTotalBusca.setText("Total da Busca: "+quantResul+" Resultado(s)");
            
            if(cont==0)//para exibir caso procura não exiba nada
                        JOptionPane.showMessageDialog(null, "Nenhum Registro encontrado");
    }//GEN-LAST:event_btnBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.ButtonGroup groupBuscarVendas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarVendas;
    private javax.swing.JLabel lblTotalBusca;
    private javax.swing.JLabel lblTotalVendido;
    private javax.swing.JRadioButton radioDataVenda;
    private javax.swing.JRadioButton radioTodasVendas;
    private javax.swing.JRadioButton radioVendasDoDia;
    private javax.swing.JRadioButton radioVendedor;
    private javax.swing.JTable tableVendas;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
