/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sof3.clinivet.frames;

import br.com.sof3.clinivet.dao.VendaDAO;
import br.com.sof3.clinivet.dao.VendasProdutosDAO;
import br.com.sof3.clinivet.dao.VendedorDAO;
import br.com.sof3.clinivet.entidade.Venda;
import br.com.sof3.clinivet.entidade.VendaProduto;
import br.com.sof3.clinivet.entidade.Vendedor;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Renan
 */
public class frmVendasEfetuadas extends javax.swing.JFrame {
    VendaDAO vdao = new VendaDAO();
    VendedorDAO vendDao = new VendedorDAO();
    VendasProdutosDAO vpdao = new VendasProdutosDAO();
    /**
     * Creates new form frmVendasEfetuadas
     */
    public frmVendasEfetuadas() {
        initComponents();
        setDefaultCloseOperation(WIDTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupBuscarVendas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTotalBusca = new javax.swing.JLabel();
        lblTotalVendido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVendas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        radioVendedor = new javax.swing.JRadioButton();
        radioVendasDoDia = new javax.swing.JRadioButton();
        radioTodasVendas = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        data = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        lblBuscarVendas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(195, 239, 198));

        jPanel2.setBackground(new java.awt.Color(214, 255, 213));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTotalBusca.setText("Total da Busca: 0 Resultado(s)");

        lblTotalVendido.setText("Total Vendido: R$ 0,00");

        tableVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Venda", "Data da Venda", "Total da Venda", "Forma de Pagamento", "Vendedor", "Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableVendas);
        tableVendas.getColumnModel().getColumn(0).setResizable(false);
        tableVendas.getColumnModel().getColumn(1).setResizable(false);
        tableVendas.getColumnModel().getColumn(2).setResizable(false);
        tableVendas.getColumnModel().getColumn(3).setResizable(false);
        tableVendas.getColumnModel().getColumn(4).setResizable(false);
        tableVendas.getColumnModel().getColumn(5).setResizable(false);

        jPanel3.setBackground(new java.awt.Color(214, 255, 213));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        groupBuscarVendas.add(radioVendedor);
        radioVendedor.setText("Vendedor");

        groupBuscarVendas.add(radioVendasDoDia);
        radioVendasDoDia.setText("Vendas do dia");

        groupBuscarVendas.add(radioTodasVendas);
        radioTodasVendas.setSelected(true);
        radioTodasVendas.setText("Todas as vendas");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(radioVendedor)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(radioVendasDoDia))
                    .add(txtBusca))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btnBuscar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(radioTodasVendas))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(radioVendedor)
                    .add(radioVendasDoDia)
                    .add(radioTodasVendas))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtBusca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnBuscar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(214, 255, 213));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Buscar por data:");

        data.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dataPropertyChange(evt);
            }
        });

        jButton1.setText("Buscar por Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(data, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 215, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jButton1))
                    .add(jLabel1))
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jButton1)
                    .add(data, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(lblTotalBusca)
                                .add(441, 441, 441)
                                .add(lblTotalVendido))
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 796, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 241, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblTotalVendido)
                    .add(lblTotalBusca))
                .addContainerGap())
        );

        lblBuscarVendas.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        lblBuscarVendas.setText("Buscar vendas");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblBuscarVendas)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(6, 6, 6)
                .add(lblBuscarVendas)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

            DefaultTableModel dtm = (DefaultTableModel)tableVendas.getModel();
            int cont = 0, quantResul = 0;
            double totalVendido = 0;
            
            int cont2 = dtm.getRowCount();
            for(int aux=cont2-1 ;   aux>=0;  aux--){//removendo valores da tabela
                dtm.removeRow(aux);
            }
            
            Venda v  = new Venda();
            List<Venda> ven = new LinkedList<Venda>();
            
          
                        
            if(radioTodasVendas.isSelected()) {
                try {
                    ven = vdao.getAllVenda();
                } catch (SQLException ex) {
                    Logger.getLogger(frmVendasEfetuadas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(radioVendedor.isSelected()) {
                try {
                   int id_vendedor;
                   id_vendedor = vendDao.getIdVendedor(txtBusca.getText());
                   ven = vdao.getVendaByVendedor(id_vendedor);
                } catch (SQLException ex) {
                    Logger.getLogger(frmVendasEfetuadas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            if(radioVendasDoDia.isSelected()) {
                try {    
                    ven = vdao.getVendasDoDia();
                } catch (SQLException ex) {
                    Logger.getLogger(frmVendasEfetuadas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            for(int aux =0;aux<ven.size();aux++){
                v.setId(ven.get(aux).getId());
                v.setDataVenda(ven.get(aux).getDataVenda());
                v.setTotalVenda(ven.get(aux).getTotalVenda());
                v.setFormaPagamento(ven.get(aux).getFormaPagamento());
                v.setVendedor(ven.get(aux).getVendedor());
                v.setCliente(ven.get(aux).getCliente());  
                        
                totalVendido += v.getTotalVenda();
                dtm.addRow(v.addTableVendasEfetuadas());
                cont++;
                quantResul++; 
            }
            
            if(ven.size()==0){
              lblTotalVendido.setText("Total Vendido: R$ 0,00");
              lblTotalBusca.setText("Total da Busca: 0 Resultado(s)");
            }
                    
            lblTotalVendido.setText("Total Vendido: R$ "+String.format("%.2f", totalVendido));
            lblTotalBusca.setText("Total da Busca: "+quantResul+" Resultado(s)");
            
            if(cont==0)//para exibir caso procura não exiba nada
                        JOptionPane.showMessageDialog(null, "Nenhum Registro encontrado");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void dataPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dataPropertyChange

    }//GEN-LAST:event_dataPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
            if(data.getDate()==null){
                JOptionPane.showMessageDialog(null, "A data não pode ser vazia!");
                return;
            }
        
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");  
            
            String dataFormatada = sdf.format(data.getDate());
            
            
                
            DefaultTableModel dtm = (DefaultTableModel)tableVendas.getModel();
            int cont = 0, quantResul = 0;
            double totalVendido = 0;
            
            int cont2 = dtm.getRowCount();
            for(int aux=cont2-1 ;   aux>=0;  aux--){//removendo valores da tabela
                dtm.removeRow(aux);
            }
            
            Venda v  = new Venda();
            List<Venda> ven = new LinkedList<Venda>();
            
            try {            
                ven = vdao.getVendaPorData(dataFormatada);
            } catch (SQLException ex) {
                Logger.getLogger(frmVendasEfetuadas.class.getName()).log(Level.SEVERE, null, ex);
            }

            for(int aux =0;aux<ven.size();aux++){
                v.setId(ven.get(aux).getId());
                v.setDataVenda(ven.get(aux).getDataVenda());
                v.setTotalVenda(ven.get(aux).getTotalVenda());
                v.setFormaPagamento(ven.get(aux).getFormaPagamento());
                v.setVendedor(ven.get(aux).getVendedor());
                v.setCliente(ven.get(aux).getCliente());                            
                        
                totalVendido += v.getTotalVenda();
                dtm.addRow(v.addTableVendasEfetuadas());
                cont++;
                quantResul++; 
            }
            
            if(ven.size()==0){
              lblTotalVendido.setText("Total Vendido: R$ 0,00");
              lblTotalBusca.setText("Total da Busca: 0 Resultado(s)");
            }
                    
            lblTotalVendido.setText("Total Vendido: R$ "+String.format("%.2f", totalVendido));
            lblTotalBusca.setText("Total da Busca: "+quantResul+" Resultado(s)");
            
            if(cont==0)//para exibir caso procura não exiba nada
                        JOptionPane.showMessageDialog(null, "Nenhum Registro encontrado");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableVendasCliMouseClicked(java.awt.event.MouseEvent evt) {                                         
        String codigoVenda;
        int idVenda;
        if (evt.getClickCount() == 2) {  
           VendaProduto vp = new VendaProduto();
           List<VendaProduto> listvp = new LinkedList<VendaProduto>();
           
           setVisible(false);
           
           
           codigoVenda = String.valueOf(tableVendas.getValueAt(tableVendas.getSelectedRow(), 0));
           
           idVenda = Integer.parseInt(codigoVenda);
            try {
                listvp = vpdao.getProdutosVendidos(idVenda);
                JOptionPane.showMessageDialog(null, listvp);
            } catch (SQLException ex) {
                Logger.getLogger(frmVendasEfetuadas.class.getName()).log(Level.SEVERE, null, ex);
            }
               
        }
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private static com.toedter.calendar.JDateChooser data;
    private javax.swing.ButtonGroup groupBuscarVendas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarVendas;
    private javax.swing.JLabel lblTotalBusca;
    private javax.swing.JLabel lblTotalVendido;
    private javax.swing.JRadioButton radioTodasVendas;
    private javax.swing.JRadioButton radioVendasDoDia;
    private javax.swing.JRadioButton radioVendedor;
    private javax.swing.JTable tableVendas;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
